# General considerations  {#overview}

## A very brief history

### Early development

Generalization of the tangent.

- P. de Fermat (1607-1665)
- I. Barrow (1630-1677)
- I. Newton (1642-1727)
- G. W. Leibnitz (1646-1716)
- B. Taylor (1685-1731)
- L. Euler (1707-1783) First to solve differential equation first order (1739)
- J-L. Lagrange (1736-1813)
- Ricati equation


### Limit concept

- J. L. Cauchy (1789-1857),  
- K. T. W. Weierstrass (1815-1897) et
- R. Lipschitz (1832-1903)


### Using geometry

- L. I. Fuchs (1833-1902)
- H. Poincaré (1854-1912),
- Stephen Smale https://en.wikipedia.org/wiki/Stephen_Smale (1930 -)

This was a big step forwards to find solutions even for complex system (using differential
geometry). But things got a bit more tricky when chaos was discover.


### Chaos

- A. Turing (1912-1954)
- E. Lorenz (1907-2008)
- Li
- Lyapunov


#### Structural stability and catastrophe theory

- R. Thom (1923-2002)
- E. C. Zeeman FRS (1925 – 2016)
- A. Andronov (1901-1952)
- L. Pontryagin (1908-1988).}


### Feuilletages

- C. Ehresmann (1905-1979)
- G. H. Reeb (1920-1993)


## Choose your computational tools

Among others:

- Julia: http://docs.juliadiffeq.org/latest/

- Octave: https://octave.org/doc/v4.0.3/Ordinary-Differential-Equations.html

- Python: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.integrate.ode.html

- Rust: https://docs.rs/GSL/0.4.26/rgsl/types/ordinary_differential_equations/index.html

- FORTRAN C/C++


### R

- R: https://cran.r-project.org/web/packages/deSolve/index.html https://www.r-pkg.org/badges/version/odeintr


### ODE with `desolve`

[deSolve](https://cran.r-project.org/web/packages/deSolve/index.html) package
is commonly used to solve ODE. I recommend you start by looking at the vignettes

- https://cran.r-project.org/web/packages/deSolve/vignettes/compiledCode.pdf
- https://cran.r-project.org/web/packages/deSolve/vignettes/deSolve.pdf
